### ISSUE TITLE
Mail Broken

### ISSUE THREAD

**Issue by cleanspin** [Politica-Para-Todos/pt-legislativas-2019-conteudo#2]
![Screenshot_20190927_232051](https://user-images.githubusercontent.com/52682995/65805555-f212f100-e17d-11e9-9e61-a91a64f9b02f.png)

Boas, não tenho a certeza se o procedimento é abrir um issue aqui. Se estiver errado corrijam-me.

Enviei um mail para o mail contacto@politicaparatodos.pt e deu-me: The recipient server did not accept our requests to connect

Steps to reproduce: send mail to contacto@politicaparatodos.pt

**Comment by nuno-carneiro** [comment]
Obrigado. Muito importante, a tentar resolver

**Comment by nuno-carneiro** [comment]
Solved, era um problema com o DNS provider. Muito obrigado pelo aviso crucial.
